spring:
  profiles:
    active: stg

---
logging:
  level:
    com: DEBUG

spring:
  profiles: stg
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:~/test
   username: sa
   password: Cwgleo2019
   
